### ISSUE TITLE
CTAN upload

### ISSUE THREAD

**Issue by mlhetland** [dudebout/matrix.skeleton#2]
Perhaps it'd be useful to upload `matrix.skeleton` to [CTAN](https://ctan.org), making it available in various LaTeX distributions out of the box? From what I can see this would entail:

1. Adding author and license information to `README.md` (this is required by CTAN; need not be added to the GitHub version, of course – just the one in the CTAN zipfile);
2. Creating a zip or tgz file with the directory named `matrix-skeleton` or the like (see below); and
3. Filling out the [CTAN upload form](https://ctan.org/upload) with the suggested path being something like `/graphics/pgf/contrib/matrix-skeleton` (dots are not permitted here) and the version either set to the release/commit date (`2014-07-23`) or actually creating a versioned release here on GitHub first.

If you'd rather not have the hassle, I'd be happy to register it for you.

**Comment by dudebout** [comment]
Thank you Magnus for your interest in `matrix.skeleton`, and for providing a clear list of required actions. I am working on a Makefile to create the required tarball.

**Comment by mlhetland** [comment]
Excellent!

**Comment by dudebout** [comment]
The Makefile is on master, and I will do the version and CTAN form shortly.

**Comment by dudebout** [comment]
I have submitted the CTAN upload form.

**Comment by mlhetland** [comment]
Seems it's now [on CTAN](https://ctan.org/pkg/matrix-skeleton). Great stuff!-)
