### ISSUE TITLE
Matrix positioning breaks matrix label and nodes drawn with matrixname-n-m nodes.

### ISSUE THREAD

**Issue by TruePath** [dudebout/matrix.skeleton#6]
Please see [here](https://tex.stackexchange.com/questions/582415/make-tikz-matrix-label-move-with-matrix) for a detailed account of the issue.

I've included the code that causes the problem

```
\documentclass[leqno]{amsart}
\usepackage{tikz}
\usetikzlibrary{matrix,calc,positioning,tikzmark,patterns,fit,matrix.skeleton}


\begin{document}
\begin{tikzpicture}
        \matrix (x) [matrix of math nodes,style contour = {draw, very thick},style grid = {draw, thin},label=above:\( X_e \),nodes in empty cells=true,ampersand replacement=\&] {
            \& \\
            \& \\
            \& \\
            \& \\
            \& \\
        };

        \matrix (m) at (4,0) [matrix of math nodes,style contour = {draw, very thick},style grid = {draw, thin},label={above:\( A \)},nodes in empty cells=true,ampersand replacement=\&] {
            \& \& \\
            \& \& \\
            \& \& \\
            \& \& \\
            \&  \& \\
        };

        \node[black] (val-m-5-3) at (m-5-3) {1};
        \node[black,circle,draw,minimum size=2.2mm] (circle-m-5-3) at (m-5-3) {};
        \fitandstyle[background]{(m-cell-1-1) (m-cell-3-1)}{fill=Gray};
        \fitandstyle[background]{(m-cell-1-2) (m-cell-3-3)}{pattern=crosshatch};
    \end{tikzpicture}

\end{document}
```

This creates the following image (note how the label and drawing doesn't move with the matrix.

<img width="597" alt="Screen Shot 2021-02-07 at 7 52 29 PM" src="https://user-images.githubusercontent.com/121223/107274534-88b41b00-6a1e-11eb-93ae-18652898b5ca.png">

Note that if I just draw the matrix m by itself without moving it I get the desired result.

<img width="119" alt="Screen Shot 2021-02-07 at 8 02 01 PM" src="https://user-images.githubusercontent.com/121223/107274609-9ff30880-6a1e-11eb-8f39-02fadbbb0baf.png">

**Comment by dudebout** [comment]
Thank you @TruePath for the bug report.

I think this is another manifestation of #1. When more than one matrix is in the `tikzpicture` element, and when the positioning `at` is used for that matrix, the border and the background (noticed thanks to your example) are displayed in the wrong location, whereas the cell content, or nodes centered around cells are displayed in the expected location.

**Comment by TruePath** [comment]
Just FYI the same thing happens if I instead position by adding the key
"right = 2cm of x" to the matrix m rather than positioning it with at.
Weirdly, it didn't seem to happen if I merely positioned is right of x
without the displacement.

P.S. I'm really benefiting from your package even with this bug so I wanted
to thank you for creating it.

**Comment by dudebout** [comment]
Happy that you find it useful!

I have tried `right of = x`, `right = 2cm of x`, and `right = of x` and I saw the same behavior: The labels end up in between `m` and `x` instead of over `m`.

**Comment by TruePath** [comment]
Sorry, I said that wrong.  I don't remember the exact command but unless I
was hallucinating I found some keys involving left/right that was a synonym
for  anchor=west and that does shift everything.  But yes, I was
misremembering when I included x in there.

**Comment by dudebout** [comment]
Thanks to @onursehitoglu, this issue has been resolved!
